### ISSUE TITLE
Undeclared identifier: 'TChromeTab' on Delphi 12 Patch 1

### ISSUE THREAD

**Issue by jwhitham1** [norgepaul/TChromeTabs#101]
V2.7 on Delphi 12 Patch 1. Demo runs fine, install seems okay, but attempting to handle events once the component is on a form results in all object erroring as undefined.

I have added TChromeTabs-2.7, TChromeTabs-2.7\GDIPlus and TChromeTabs-2.7\Lib to the Library Paths.

**Comment by landrix** [comment]
Sry, I can't find any error. Have you used ChromeTabs before Patch 1? Can you create an example that replicates the error?

**Comment by jwhitham1** [comment]
Thank you for the reply. Problem was I hadn't added all required units to my form uses clause. All working fine now.
