### ISSUE TITLE
Wrong LibVersion for Delphi 12 Packages

### ISSUE THREAD

**Issue by carloBarazzetta** [norgepaul/TChromeTabs#105]
Unit ChromeTabs_R.dpk and ChromeTabs_D.dpk:
line 29 {$LIBVERSION '350'} -> {$LIBVERSION '290'} 
For Delphi 12 should be 290 (as in Delphi 11=280, Delphi 10.4=270)
thanks.

**Comment by landrix** [comment]
thanks
