### ISSUE TITLE
remove versions.inc

### ISSUE THREAD

**Issue by landrix** [norgepaul/TChromeTabs#21]
What do you think about removing the versions.inc file?

then replace all

{$IFDEF DELPHI2006_UP}

with 

{$IF CompilerVersion >= 18.0}

**Comment by norgepaul** [comment]
Thanks... I saw your pull request. I seem to remember switching to CompilerVersion, but having issues with Delphi 7. Have you tested it with Delphi 7?

**Comment by landrix** [comment]
you can take the pull request...

i have tested it with Delphi 6
my fork contains more little changes for this version

**Comment by norgepaul** [comment]
Hi Sven. I finally got around to merging your changes. Many thanks. I'll try to be quicker next time :)

**Comment by landrix** [comment]
No problem, everyone, as he has time.
