### ISSUE TITLE
EReadError with error: chrtabs.Options.Display.Addbutton.HorizontalOffsetFlaoting: Property does not exist

### ISSUE THREAD

**Issue by rsjmeijer** [norgepaul/TChromeTabs#24]
I have installed earlyer an older version of your Chrome tabs. And now i deleted that, installed the new one but i get this error:

chrtabs.Options.Display.Addbutton.HorizontalOffsetFloating: Property HorizontalOffsetFloating does not exist.

What went wrong??

Kind regards,

Robert Meijer

**Comment by rsjmeijer** [comment]
This is with Delphi XE-2. I tried allso this with a new project, but here it allso went wrong.

**Comment by norgepaul** [comment]
Hi,

It sounds like you need to install the TChromeTabs component again. Then,
if the error is displayed when opening a form with a TChromeTabs component
on it you should click ignore. Delphi is just telling you that the property
no longer exists.

Cheers,
Paul

**Comment by rsjmeijer** [comment]
Hello Paul,

Thank you for the quick response!!

I did remove the component, and all of the files from Chrometab.

Then reinstalled the component again. Opend a new project, new form, place the chrometab on it. No errors. When I Compile it, then I get this error:

[cid:image001.png@01D093DC.4DA21360]

I didn’t changed a this on the component, just place it on the form, and compile.
Kind regards,
Robert S.J. Meijer
[Auducom]<http://www.auducom.nl/>





[http://www.auducom.nl/email_images/home.png]

Edyweg 12<https://maps.google.nl/maps?q=edyweg+12+spankeren&ll=52.055631,6.11034&spn=0.003411,0.008256&hnear=Edyweg+12,+6956+BB+Spankeren,+Rheden,+Gelderland&gl=nl&t=h&z=18&iwloc=A>



6956 BB Spankeren<https://maps.google.nl/maps?q=edyweg+12+spankeren&ll=52.055631,6.11034&spn=0.003411,0.008256&hnear=Edyweg+12,+6956+BB+Spankeren,+Rheden,+Gelderland&gl=nl&t=h&z=18&iwloc=A>









[http://www.auducom.nl/email_images/telefoon.png]

+31(0)313 727 990<tel:31313727990>



[http://www.auducom.nl/email_images/fax.png]

+31(0)313 727 999<Fax:+31313727999>



[http://www.auducom.nl/email_images/gsm.png]

+31(0)653 42 90 95<tel:31653429095>









[http://www.auducom.nl/email_images/www.png]

www.auducom.nl<http://www.auducom.nl/>



[http://www.auducom.nl/email_images/linkedin.png]

LinkedIn<http://nl.linkedin.com/pub/robert-meijer/0/52b/78/nl>









Bezoek ook onze website<http://www.auducom.nl/>



Van: Paul Spencer Thornton [mailto:notifications@github.com]
Verzonden: donderdag 21 mei 2015 15:22
Aan: norgepaul/TChromeTabs
CC: Robert S.J. Meijer
Onderwerp: Re: [TChromeTabs] EReadError with error: chrtabs.Options.Display.Addbutton.HorizontalOffsetFlaoting: Property does not exist (#24)

Hi,

It sounds like you need to install the TChromeTabs component again. Then,
if the error is displayed when opening a form with a TChromeTabs component
on it you should click ignore. Delphi is just telling you that the property
no longer exists.

Cheers,
Paul

**Comment by norgepaul** [comment]
Hi

I did remove the component, and all of the files from Chrometab.
>
> Then reinstalled the component again. Opend a new project, new form, place
> the chrometab on it. No errors. When I Compile it, then I get this error:
>
> [cid:image001.png@01D093DC.4DA21360]
>

This doesn't look like an error that could come from TChromeTabs. It looks
like some internal Delphi issue. Can you send me a screenshot?

/Paul

**Comment by rsjmeijer** [comment]
Hello Paul,

When I open the _r file and try to compile it the following error occurs:


[cid:image001.png@01D093DD.B68242F0]


The code with the error is:  {$IF CompilerVersion >= 28}System.Types,{$ENDIF}

When I change the code (as the comile error says) to: {$IF CompilerVersion >= 28}System.Types,{$IFEND}

It compiles fine. This also happen with the _D file, same problem.

From what you want an screenshot?
Kind regards,
Robert S.J. Meijer
[Auducom]<http://www.auducom.nl/>





[http://www.auducom.nl/email_images/home.png]

Edyweg 12<https://maps.google.nl/maps?q=edyweg+12+spankeren&ll=52.055631,6.11034&spn=0.003411,0.008256&hnear=Edyweg+12,+6956+BB+Spankeren,+Rheden,+Gelderland&gl=nl&t=h&z=18&iwloc=A>



6956 BB Spankeren<https://maps.google.nl/maps?q=edyweg+12+spankeren&ll=52.055631,6.11034&spn=0.003411,0.008256&hnear=Edyweg+12,+6956+BB+Spankeren,+Rheden,+Gelderland&gl=nl&t=h&z=18&iwloc=A>









[http://www.auducom.nl/email_images/telefoon.png]

+31(0)313 727 990<tel:31313727990>



[http://www.auducom.nl/email_images/fax.png]

+31(0)313 727 999<Fax:+31313727999>



[http://www.auducom.nl/email_images/gsm.png]

+31(0)653 42 90 95<tel:31653429095>









[http://www.auducom.nl/email_images/www.png]

www.auducom.nl<http://www.auducom.nl/>



[http://www.auducom.nl/email_images/linkedin.png]

LinkedIn<http://nl.linkedin.com/pub/robert-meijer/0/52b/78/nl>









Bezoek ook onze website<http://www.auducom.nl/>



Van: Paul Spencer Thornton [mailto:notifications@github.com]
Verzonden: donderdag 21 mei 2015 15:44
Aan: norgepaul/TChromeTabs
CC: Robert S.J. Meijer
Onderwerp: Re: [TChromeTabs] EReadError with error: chrtabs.Options.Display.Addbutton.HorizontalOffsetFlaoting: Property does not exist (#24)

Hi

I did remove the component, and all of the files from Chrometab.
>
> Then reinstalled the component again. Opend a new project, new form, place
> the chrometab on it. No errors. When I Compile it, then I get this error:
>
> [cid:image001.png@01D093DC.4DA21360]
>

This doesn't look like an error that could come from TChromeTabs. It looks
like some internal Delphi issue. Can you send me a screenshot?

/Paul

**Comment by norgepaul** [comment]
Ah, I see what happened. Your original image was stripped out of the email
for some reason.

Here's what I see:


> When I open the _r file and try to compile it the following error occurs:
>
> [cid:image001.png@01D093DD.B68242F0]
>

:)

Do you have {$LEGACYIFEND ON} turned on anywhere?

See this article for more info -
http://blog.blong.com/2012/10/new-compiler-directives-in-delphi-xe3.html

Cheers,
Paul

**Comment by rsjmeijer** [comment]
Hello Paul,

I use Delphi XE-2, not XE-3.

The option {$LEGACYIFEND ON} does no exist in the files I use.
Somehow after deinstalling, and removing the old files (again) and install the new version now it works suddenly.
I have changed the code (as the comile error says) to: {$IF CompilerVersion >= 28}System.Types,{$IFEND} of both files ( _s and _D). Then copied the dcu file to my project location and now it works fine.

Strange, because before it didn’t work.
Thanks for the support!!!!
Kind regards,
Robert S.J. Meijer
[Auducom]<http://www.auducom.nl/>





[http://www.auducom.nl/email_images/home.png]

Edyweg 12<https://maps.google.nl/maps?q=edyweg+12+spankeren&ll=52.055631,6.11034&spn=0.003411,0.008256&hnear=Edyweg+12,+6956+BB+Spankeren,+Rheden,+Gelderland&gl=nl&t=h&z=18&iwloc=A>



6956 BB Spankeren<https://maps.google.nl/maps?q=edyweg+12+spankeren&ll=52.055631,6.11034&spn=0.003411,0.008256&hnear=Edyweg+12,+6956+BB+Spankeren,+Rheden,+Gelderland&gl=nl&t=h&z=18&iwloc=A>









[http://www.auducom.nl/email_images/telefoon.png]

+31(0)313 727 990<tel:31313727990>



[http://www.auducom.nl/email_images/fax.png]

+31(0)313 727 999<Fax:+31313727999>



[http://www.auducom.nl/email_images/gsm.png]

+31(0)653 42 90 95<tel:31653429095>









[http://www.auducom.nl/email_images/www.png]

www.auducom.nl<http://www.auducom.nl/>



[http://www.auducom.nl/email_images/linkedin.png]

LinkedIn<http://nl.linkedin.com/pub/robert-meijer/0/52b/78/nl>









Bezoek ook onze website<http://www.auducom.nl/>



Van: Paul Spencer Thornton [mailto:notifications@github.com]
Verzonden: donderdag 21 mei 2015 16:02
Aan: norgepaul/TChromeTabs
CC: Robert S.J. Meijer
Onderwerp: Re: [TChromeTabs] EReadError with error: chrtabs.Options.Display.Addbutton.HorizontalOffsetFlaoting: Property does not exist (#24)

Ah, I see what happened. Your original image was stripped out of the email
for some reason.

Here's what I see:


> When I open the _r file and try to compile it the following error occurs:
>
> [cid:image001.png@01D093DD.B68242F0]
>

:)

Do you have {$LEGACYIFEND ON} turned on anywhere?

See this article for more info -
http://blog.blong.com/2012/10/new-compiler-directives-in-delphi-xe3.html

Cheers,
Paul

**Comment by norgepaul** [comment]
That's great.

Cheers,
Paul

**Comment by landrix** [comment]
i think it should be

{$IF CompilerVersion >= 28.0}System.{$IFEND}Types,
