### ISSUE TITLE
ChromeTabsGlassForm compilation fails

### ISSUE THREAD

**Issue by ErikVirtel** [norgepaul/TChromeTabs#26]
Due to the latest changes from September 3, 2014 _ChromeTabsGlassForm.pas_ is not compilable anymore.

In Line 34 of ChromeTabsGlassForm.pas `{$ENDIF}` was used instead of the correct `{$IFEND}`

**Comment by landrix** [comment]
Do you use an older delphi Version?

**Comment by ErikVirtel** [comment]
Delphi XE2.

**Comment by norgepaul** [comment]
Can you try the new version and see if it compiles?

**Comment by ErikVirtel** [comment]
Since there is still the `ENDIF` statement, the behavior did not change.

But I have found some information about the issue.

http://docwiki.embarcadero.com/RADStudio/XE8/en/Legacy_IFEND_(Delphi)

> At the XE4 release, the Delphi compilers were changed to accept either $IFEND or $ENDIF to close $IF statements. Before XE4, only $IFEND could be used to close $IF statements.
 
My point is, when you introduced these compiler switches on 2014-09-03, you used `IFEND` in every other file but only in `ChromeTabsGlassForm` `ENDIF` was used.

**Comment by landrix** [comment]
seemingly some merge problems

look at this repo

https://github.com/landrix/TChromeTabs

**Comment by norgepaul** [comment]
Hi Sven,

> seemingly some merge problems
>
> look at this repo
>
> https://github.com/landrix/TChromeTabs
>

Yes, we merged in some changes yesterday, but they're working fine for me.
Can you be more specific about the issues you're having?

/Paul

**Comment by landrix** [comment]
My unit ChromeTabsGlassForm;

uses
  Windows, Messages, SysUtils, Classes, Forms, Controls,
  {$IF CompilerVersion >= 28.0}System.{$ifend}Types,
  ChromeTabs;


your unit ChromeTabsGlassForm;

 {$IF CompilerVersion >= 28.0}
  System.Types,
  {$else}
  Types,
  {$endif}

git shows no different? why?

**Comment by norgepaul** [comment]
Sorry, you'd need to ask GitHub support.
