### ISSUE TITLE
TChromeTabsGlassForm reads from uninitialized local variable

### ISSUE THREAD

**Issue by igelbox** [norgepaul/TChromeTabs#29]
procedure TChromeTabsGlassForm.WMNCHitTest(var Message: TWMNCHitTest);
variable - IconRect

Sometimes this causes WM_CLOSE when double-clicking on window title
![double-clicking region](https://cloud.githubusercontent.com/assets/5264687/8428602/78e0023a-1f28-11e5-9afb-232486c27f6b.jpg)

**Comment by norgepaul** [comment]
Sorry, I'm unable to reproduce the problem. Can you send me a small demo?

**Comment by igelbox** [comment]
This problem reproduced only sometimes (because it depends on previous stack-memory-cell values), Therefore i cannot make a demo.
But this error is obvious from the static code analysis: local variable "IconRect" is never initialised but used in "if (ClientPos.X < IconRect.Right) and".

**Comment by mksjgj** [comment]
did this bug fixed? but the IconRect is still uninitialized before accessing it.

**Comment by landrix** [comment]
No further findings.

**Comment by mksjgj** [comment]
if you check the code carefully, you can find the pitfall: 
unit: ChromeTabsGlassForm.pas
method: TChromeTabsGlassForm.WMNCHitTest
local variable: IconRect  
your code read this local variable before initialize it:
   if (ClientPos.X < IconRect.Right) and ... 

i can not express it more clearly

**Comment by landrix** [comment]
i found some infos and an old issue about this

#5 

https://stackoverflow.com/questions/40041013/caption-buttons-not-respond-to-mouse-clicks-after-non-client-painting-with-dwm

i've added

`IconRect := GetSysIconRect;`
