### ISSUE TITLE
XE8 ChromeTabsDemo compile error

### ISSUE THREAD

**Issue by bdwilton** [norgepaul/TChromeTabs#31]
Hey,
Just compiling under XE8 (not update 1 yet) and get the following errors when compiling the Demo

[dcc32 Error] frmMainU.pas(44): E2004 Identifier redeclared: 'System.Actions'
[dcc32 Fatal Error] ChromeTabsDemoXE8.dpr(5): F2063 Could not compile used unit 'frmMainU.pas'

Just for further detail it has some warnings with the {$ifend} saying Legacy consider changing to $ENDIF or enable $LEGACYIFEND

All minor issues but thought I'd mention them.

**Comment by norgepaul** [comment]
This should now be fixed
