### ISSUE TITLE
Support for Delphinus (Delphi package manager)

### ISSUE THREAD

**Issue by landrix** [norgepaul/TChromeTabs#32]
https://github.com/Memnarch/Delphinus

**Comment by norgepaul** [comment]
Right now I have very little time to work on TChromeTabs. However, I would love to add it to Delphinus. If you want to add the required files I will happily submit it.

**Comment by landrix** [comment]
ok, i will test it in my fork :)

**Comment by landrix** [comment]
would you give me temporary write access to TChromeTabs? Delphinus allowed only original repositories on github, no forks. There may be the need to make adjustments to the packages and it would accelerate the testing.

**Comment by norgepaul** [comment]
I'm happy to give you permanent access if you like. Done :)

**Comment by landrix** [comment]
Thanks
