### ISSUE TITLE
Delphinus installation files have no Delphi Seattle information

### ISSUE THREAD

**Issue by Memnarch** [norgepaul/TChromeTabs#33]
A few days ago, Delphi Seattle support was added to TChromeTabs (according to the commits). However, the given information is still missing for the Delphinus Installer. In the future, incompatible Package will not showup until compatible in the UI. (Currently TChromeTabs is still listed)

**Comment by landrix** [comment]
ok, i'll take a look later

**Comment by norgepaul** [comment]
Great, thanks

**Comment by landrix** [comment]
should work now

**Comment by Memnarch** [comment]
Thanks(Haven't tried it yet myself). Something you can do is, specify only minversion for package_Compiler and compiler and specify only the min version for the most recent grouproject. Usually the projectstructure does not change that much and is mostly compatible with older ones when a new Delphi is released. I did that for my AsciiImage and so far, the XE6 project compiles fine for recent delphi versions. This removes the need to respond instantly for each release of Delphi
