### ISSUE TITLE
Tab widths set by content not working

### ISSUE THREAD

**Issue by Andyk123** [norgepaul/TChromeTabs#36]
Tabs with images overwrite the tab text.

Problem is in  TChromeTabControl.CalculateRects, I have fixed the problem by effectively commenting out the following code.....

 if {LeftOffset + ImageWidth > RightOffset} false then
  begin
    NormalImageVisible := FALSE;
    OverlayImageVisible := FALSE;
    SpinnerVisible := FALSE;
  end

**Comment by norgepaul** [comment]
Fixed
