### ISSUE TITLE
Delete Tab logic faulty when tab is flanked by invisible tabs.

### ISSUE THREAD

**Issue by Andyk123** [norgepaul/TChromeTabs#37]

**Comment by Andyk123** [comment]
When a tab is deleted, the active tab becomes the tab to the left of the deleted tab. The tab becomes active even if it is invisible. This forces the renderer to draw the invisible tab.

I fixed the problem with following code change in TChromeTabsList.DeleteTab

    if NewIdx > Count - 1 then
      NewIdx := Count - 1;
    while (NewIdx<>-1) and not(Items[NewIdx].visible) do
      dec(NewIdx);
    if NewIdx <> -1 then
      Items[NewIdx].Active := TRUE;

**Comment by norgepaul** [comment]
Fixed
