### ISSUE TITLE
HideCloseButton property value lost when tab is dragged between controls

### ISSUE THREAD

**Issue by pokroops** [norgepaul/TChromeTabs#38]
TCustomChromeTabs.InsertDroppedTab does not copy 
HideCloseButton property value to newly created TChromeTab instance.

suggested fix:

--- Lib/ChromeTabs.pas
+++ Lib/ChromeTabs.pas
@@ -711,6 +711,7 @@ begin
       Result.ImageIndexOverlay := FActiveDragTabObject.DragTab.ImageIndexOverlay;
       Result.Pinned := FActiveDragTabObject.DragTab.Pinned;
       Result.SpinnerState := FActiveDragTabObject.DragTab.SpinnerState;
+      Result.HideCloseButton := FActiveDragTabObject.DragTab.HideCloseButton;
       Result.Tag := FActiveDragTabObject.DragTab.Tag;
       Result.Visible := FActiveDragTabObject.DragTab.Visible;
       Result.Modified := FActiveDragTabObject.DragTab.Modified;
--

**Comment by norgepaul** [comment]
Fixed
