### ISSUE TITLE
Tabs not immediately shifting after deleting tab

### ISSUE THREAD

**Issue by djjd47130** [norgepaul/TChromeTabs#46]
Scenario: A number of tabs are open at once. I use the `OnButtonCloseTabClick` event, and I forcefully always set `Close := False;` here, and manually perform the deletion myself by calling `Tabs.Tabs.Delete(TabIndex);`.

The problem is that if I delete a tab in the middle of all the open tabs, that tab does get deleted, but then there's a big gap between the two tabs to the side, where that tab used to be. If I move the mouse around, or select another tab, then suddenly that empty space gets corrected.

**Comment by djjd47130** [comment]
Is there any progress on this?

**Comment by landrix** [comment]
i will look at this

**Comment by norgepaul** [comment]
Thanks Sven.

**Comment by landrix** [comment]
you must call 

```
ChromeTabs1.Tabs.DeleteTab(indexToDelete,true);
ChromeTabs1.InvalidateAllControls;
```
