### ISSUE TITLE
AccessViolation when loading from DLL

### ISSUE THREAD

**Issue by ghost** [norgepaul/TChromeTabs#50]
When loading the control within a DLL there will be an access violation and the program crashes.

The problem is described here:
https://steema.com/wp/blog/2014/03/12/teechart-and-gdi-inside-a-dll/

And the fix:

> initialization
>   StartupInput.DebugEventCallback := nil;
>   StartupInput.SuppressBackgroundThread := False;
>   StartupInput.SuppressExternalCodecs := False;
>   StartupInput.GdiplusVersion := 1;
>   GdiplusStartup(gdiplusToken, @StartupInput, nil);

**Comment by norgepaul** [comment]
Thanks for the info
