### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by Memnarch** [norgepaul/TChromeTabs#52]
Hi,
Just noticed that the current source is oficcially 2.3, but there is no release for the given commit. Is it possible to add the releases here aswell? This allows Delphinus to list them.

EDIT: Ofcourse, this works only if the Delphinus-Files were already commited at this time.

**Comment by norgepaul** [comment]
Hi,

I've never worked with the Delphinus integration, but if you tell me what to change I can sort it out.

Cheers,
Paul

**Comment by Memnarch** [comment]
As long as the Delphinus files are still valid (searchpathes correct, all current projects for packages included, which seems correct) all you have to do is create a release here on Github. Use a commit which includes the Delphinus files and give it an appropriate versionnumber. That should do it :).
https://github.com/Memnarch/Delphinus/wiki/Versioning-your-package

The only thing about the delphinus files that is currently odd is that the grouproj-files include the demo which results in Delphinus building it. Which is quite unnecessary. Besides if the demo (at one point) fails to build, Delphinus will fail. But currently it looks fine.

If you want to know more about what goes where in my files, there is a WIkipage on my project:
https://github.com/Memnarch/Delphinus/wiki
If you have any questions or something is unclear, don't hesitate to ask me :)

**Comment by landrix** [comment]
anything more to do? or can i close this issue?

**Comment by Memnarch** [comment]
Looks good :)
