### ISSUE TITLE
On the windows XP the icons background color does show problems

### ISSUE THREAD

**Issue by sqlnew** [norgepaul/TChromeTabs#53]
When the TChromeTabs  work on the windows xp, the title icons background color display problems.
And it work normal in Win7,
I do not know what the reason is, please repair the next BUG, thank you very much.

**Comment by landrix** [comment]
sorry, i don't use Windows XP anymore. you should provide a patch.

**Comment by sqlnew** [comment]
Now i have fix it on the xp, modify ChromeTabsControls.pas. thank you again.

**Comment by landrix** [comment]
do you have a patch?  what do have changed?
