### ISSUE TITLE
Hi, can you add a element for the THitTestArea and a event TOnTabImageClick?

### ISSUE THREAD

**Issue by mksjgj** [norgepaul/TChromeTabs#57]
Hi, 
  thank for your wonderful work, I had deceided change my code from TIceTabSet to your TChromeTabs,
but TChromeTabs lacks for a feature  i relied on: a event when the tab image clicked -- just like the TOnButtonCloseTabClick.
if you do have not enougth spare time, i can try it and post it to you. but i think you can do it better and efficiently  ^__^ 

thanks again.

**Comment by mksjgj** [comment]
does anyone care this feature?

**Comment by landrix** [comment]
Is that still relevant?

**Comment by mksjgj** [comment]
Yes, I had added this myself, pls check the code marked //n9p
[Lib.zip](https://github.com/norgepaul/TChromeTabs/files/5853186/Lib.zip)

**Comment by mksjgj** [comment]
i wish you merge it to your office version

**Comment by landrix** [comment]
thanks, great work
