### ISSUE TITLE
bug(spell error?) in TChromeTabControl.CalculateRects

### ISSUE THREAD

**Issue by mksjgj** [norgepaul/TChromeTabs#58]
if OverlayImageVisible then
  begin
    if ChromeTabs.GetImagesOverlay.Width > ChromeTabs.GetImagesOverlay.Width then
      ImageWidth := ChromeTabs.GetImagesOverlay.Width;

    if ChromeTabs.GetImagesOverlay.Height > ChromeTabs.GetImagesOverlay.Height then
      ImageHeight := ChromeTabs.GetImagesOverlay.Height;
  end;

i think it should be:

  if OverlayImageVisible then
  begin
    if ChromeTabs.GetImagesOverlay.Width > ChromeTabs.**GetImages**.Width then
      ImageWidth := ChromeTabs.GetImagesOverlay.Width;

    if ChromeTabs.GetImagesOverlay.Height > ChromeTabs.**GetImages**.Height then
      ImageHeight := ChromeTabs.GetImagesOverlay.Height;
  end;

**Comment by mksjgj** [comment]
a better way:

if OverlayImageVisible then
begin
if ChromeTabs.GetImagesOverlay.Width > ImageWidth  then
ImageWidth := ChromeTabs.GetImagesOverlay.Width;

if ChromeTabs.GetImagesOverlay.Height > ImageHeight  then
  ImageHeight := ChromeTabs.GetImagesOverlay.Height;

end;

**Comment by landrix** [comment]
fixed in next release

currently here

https://github.com/norgepaul/TChromeTabs/tree/monitorv2support
