### ISSUE TITLE
initialize TChromeTab.data before add

### ISSUE THREAD

**Issue by kormizz** [norgepaul/TChromeTabs#65]
Is that possible? Thank you! :)

**Comment by par4dise** [comment]
Do you mean that you need an event triggering before `TChromeTabsList.Add` is executed? (in ChromeTabsClasses.pas)

**Comment by kormizz** [comment]
No, I need to create TChromeTab and initialize its data property and other stuff before it's added to collection... I need to have all tabs in the collection fully initialized.
Something like:
TChromeTabsList.Add(atab: TChromeTab)

**Comment by landrix** [comment]
I don't understand. TChromeTab.data is for userdefined data. What should be initialized there before? On nil?

**Comment by kormizz** [comment]
Actual situation:
```
tab := tabs.Add; //events are fired here -> data property is nil
tab.data := SomeData;
```

What I need is this:
```
tab := TChromeTab.Create();
tab.data := SomeData;
tabs.add(tab);
```

Or this:
```
tab := tabs.Add(SomeData); //events are fired here, but after data property initialization
```

**Comment by landrix** [comment]
Which event is triggered on tabs.Add? Which you need with .Data?

**Comment by kormizz** [comment]
fe.: OnActiveTabChanged

**Comment by landrix** [comment]
try this:

Exclude ActivateNewTab from TChromeTabs.Options.Behavior

and

```
  ct := ChromeTabs.Tabs.Add;
  ct.Caption := _('Suchen');
  ct.Data := ...;
  ChromeTabs.ActiveTab := ct;
```

**Comment by kormizz** [comment]
ok thx :)
