### ISSUE TITLE
Add and Close buttons display incorrectly under High DPI

### ISSUE THREAD

**Issue by stephenfewer** [norgepaul/TChromeTabs#72]
When creating a TChromeTab control at run-time for a system DPI aware application, the close tab buttons and add button are not displayed as expected. See attached screenshot. This is using the latest source from master, running under a 2560x1440 display scaled at 200%.

![tchrometabs_highdpi](https://user-images.githubusercontent.com/1172185/53258599-eda4c800-36c4-11e9-962a-ddb2f5df443e.jpg)

I have not been able to come up with a solution for this, any ideas appreciated.

**Comment by landrix** [comment]
Thank you 👍
