### ISSUE TITLE
No Chrome tabs in win 7 + XP Theme

### ISSUE THREAD

**Issue by Johnyy45** [norgepaul/TChromeTabs#74]
Hello.
Does TChromeTabs support Windows 7 oldschool theme?
This is screenshot of SrwIron (Chrome browser) and demo application.
Tabs is not located in Caption.

![1](https://user-images.githubusercontent.com/44755939/57181864-84a2b300-6eb2-11e9-9d0c-d2b3a1551536.png)

**Comment by landrix** [comment]
i think not
