### ISSUE TITLE
how to customize button's shape,please?

### ISSUE THREAD

**Issue by kxzhe** [norgepaul/TChromeTabs#79]
hi,dear!now the close button's shape is a circle,and the add button's shape is a parallelogram，i want to make them a rectangle, could you tell me how to do that? i'm a beginner of delphi, could you give me some sample code? Thank you very much!!

sorry for my poor english. i just want to say this is the best component i have ever used. Really thank you very much!

**Comment by landrix** [comment]
Read the sources and find the place, where the parts will be drawn. Is it a good lesson for you to learn delphi and understand the basics for components.

**Comment by wpostma** [comment]
This component is free and open source. Fix yourself.

**Comment by landrix** [comment]
I think we can close here.
