### ISSUE TITLE
Delphi XE2 not supported?

### ISSUE THREAD

**Issue by devsskspiral** [norgepaul/TChromeTabs#89]
Try to install on DXE2, got mass compiling error:

    ChromeTabs_XE2_R.dpk   
[DCC Error] ChromeTabsUtils.pas(34): E2029 $IFEND expected but $ENDIF found
[DCC Error] ChromeTabsTypes.pas(32): E2029 $IFEND expected but $ENDIF found
[DCC Error] ChromeTabsTypes.pas(35): E2029 $IFEND expected but $ENDIF found
[DCC Error] ChromeTabsTypes.pas(56): E2029 $ENDIF expected but $IFEND found
[DCC Fatal Error] ChromeTabsUtils.pas(64): F2063 Could not compile used unit 'ChromeTabsTypes.pas'
Failed
Elapsed time: 00:00:00.4

try to repair -  got another errors.

**Comment by landrix** [comment]
Which other errors?

**Comment by landrix** [comment]
fixed
