### ISSUE TITLE
Tab fonts are too large when High-DPI awareness is enabled

### ISSUE THREAD

**Issue by haimgel** [norgepaul/TChromeTabs#94]
On Delphi 10.4, when High-DPI awareness is enabled in the manifest, the tab fonts are drawn too large. This seems to be related to [this commit|adf5f73a48a4f7c13e03d276150c0096405578d0] -- I make `ScaledFontSize` a no-op (returning same size) and font rendering became normal again.

Tested on a monitor with font scaling set to 200%.

**Comment by IgitBuh** [comment]
I can confirm that with Delphi 11. Running the application on a 200% high-dpi scale monitor results in huge tabs.
Notice, that this does not only affect text but also icons, so fixing `ScaledFontSize` isn't enough.
As a quick fix, manual scaling can be dropped completely. Delphi seems to do this already, so we don't need to do this twice.

```
function TCustomChromeTabs.ScaledPixels(pPixels: Integer): Integer;
begin
  // Font amd icons are scaled twice and become too large
  // Result := MulDiv(pPixels, {$ifdef CURRENT_PPI_SUPPORT}Self.FCurrentPPI{$else}Screen.PixelsPerInch{$ENDIF}, 96);
  Result := pPixels;
end;
```

**Comment by xelnaga64** [comment]
Thank you for the quick fix. It fixes the large font size, but X and Plus signs are too small. Can you someone please fix the issue??

<img width="239" alt="chrometabs" src="https://user-images.githubusercontent.com/39432041/185750246-764671c9-311e-44c7-b437-8e3a47435371.png">

**Comment by landrix** [comment]
https://github.com/norgepaul/TChromeTabs/blob/c6ee68a865db374e9a8fff7d02729f9985338ab3/Lib/ChromeTabs.pas#L2840

**Comment by IgitBuh** [comment]
@landrix I might be missing something, but did you actually change something regarding this issue? Your link shows the unchanged line of code that is still causing the described issue.

**Comment by landrix** [comment]
Sry, but the quickfix isn't the solution. It brings side effects when drawing the component. You can also see this in the screenshots above.
I think TChromeTab cannot be made HighDPI capable in a simple way. The component needs a complete redesign. The point about different DPI for multiple monitors would also be important. There are still several active issues related to this topic. The use of [timers](https://github.com/norgepaul/TChromeTabs/issues/92) for drawing also needs to be reconsidered. 

Contributions are welcome.

**Comment by xelnaga64** [comment]
I tested the current version today. I confirm tab fonts are still too large when high-DPI awareness is enabled.

**Comment by xelnaga64** [comment]
The current ScaledFontSize function works terribly. I use this:

`function TCustomChromeTabs.ScaledFontSize(fFontSize: Integer): Integer;
begin
  Result:=fFontSize;
end;`

**Comment by xelnaga64** [comment]
Could someone with a 4K monitor please test my proposed fix? I've verified that it runs perfectly on my end across Delphi 10 through 13. Since this has been an ongoing issue for a while, it would be great to get some secondary confirmation so we can finally get it merged.

**Comment by xelnaga64** [comment]
This code worked fine on single-monitor setups (4K, HD, etc.), but issues arose when moving the app to other monitors.
```
function TCustomChromeTabs.ScaledFontSize(fFontSize: Integer): Integer;
begin
  Result:=fFontSize;
end;
```

Here is a more robust solution for multi-monitor setups:

**ChromeTabs.pas**
```
function TCustomChromeTabs.ScaledFontSize(fFontSize: Integer): Integer;
begin
  Result := MulDiv(fFontSize,
    {$IFDEF CURRENT_PPI_SUPPORT}Self.FCurrentPPI{$ELSE}Screen.PixelsPerInch{$ENDIF},
    72);
end;
```

**ChromeTabsControls.pas**

(1) Find this:
```
TabsFont := TGPFont.Create(FChromeTabControlPropertyItems.StopTabProperties.FontName,
                           FChromeTabs.ScaledFontSize(FChromeTabControlPropertyItems.CurrentTabProperties.FontSize));
```
Replace with:
```
TabsFont := TGPFont.Create(
  FChromeTabControlPropertyItems.StopTabProperties.FontName,
  FChromeTabs.ScaledFontSize(FChromeTabControlPropertyItems.CurrentTabProperties.FontSize),
  FontStyleRegular,
  UnitPixel
);
```

(2) Find this:
`TabsFont := TGPFont.Create(FChromeTabControlPropertyItems.StopTabProperties.FontName, TextSize);`

Replace with:
```
TabsFont := TGPFont.Create(
  FChromeTabControlPropertyItems.StopTabProperties.FontName,
  TextSize,
  FontStyleRegular,
  UnitPixel
);
```
