### ISSUE TITLE
TChromeTabs on Delphi 7: bad rendering of images in Tabs

### ISSUE THREAD

**Issue by mirandaelfi** [norgepaul/TChromeTabs#97]
I am using TChromeTabs by Paul Spencer Thornton on Delphi 7 and I have a problem that I cannot solve: when I want to display images in TChromeTab, they are displayed with poor graphics, with **few colors**.

![1](https://user-images.githubusercontent.com/93582876/139825667-442b297b-8b6e-4bc6-ad61-9f81c8b80f10.png)

However, the images are **displayed correctly** in the Object Inspector, 

![2](https://user-images.githubusercontent.com/93582876/139825672-75f7ecb0-850a-46a6-a593-1968296a6b8c.png)

and if I open the TImageList component, the images are **also displayed correctly** here, even when the application is running.

![3](https://user-images.githubusercontent.com/93582876/139825676-b4028082-9bf9-4fcb-bc2e-69ec4f9c93ec.png)

Notice that the first time I opened the TImageList editor this **hint message appeared** and I answered Yes. 

![4](https://user-images.githubusercontent.com/93582876/139825680-8675a4fa-7550-49ef-9714-ca531b8a0e0f.png)

If in the same dialog box instead I answer No, the images appear **like this** (on a black background) .

![5](https://user-images.githubusercontent.com/93582876/139825681-c38cf88b-8f4b-41a8-ba40-a988ed345161.png)

The project is ChromeTabsDemoD7.dpr downloaded from the developer's site.

I couldn't find a solution to this problem anywhere online, and I don't know how to fix it, can anyone help me?

I did an alternative test with a new application, with a TPageControl and a TImageList: loading the TImageList with images and setting the ImageIndex property of a TTabSheet, the image appears drawn correctly on the tab.

Note: Delphi 7 with CnPack.

**Comment by witchole** [comment]
Could this be related to [issue #10](https://github.com/norgepaul/tchrometabs/issues/10)?

**Comment by witchole** [comment]
> Could this be related to [issue #10](https://github.com/norgepaul/tchrometabs/issues/10)?

Yes; the problem is solved by using the pngImage library provided with JVCL.
You need to enable the USE_PNGIMAGE define in ChromeTabsUtils.pas

![Capture](https://user-images.githubusercontent.com/5339981/140422982-ce8b4fba-a308-49cb-addb-2cd701b032b5.PNG)

**Comment by JavierusTk** [comment]
You gave a solution, so this issue should be closed
