### ISSUE TITLE
Does not compile under 11.2

### ISSUE THREAD

**Issue by yesilcimenahmet** [norgepaul/TChromeTabs#99]
Hi, 

As the title suggests, the Design pack does not compile, also the Icon.dcr file is missing but I have added it to the required folder. Delphi compiler gives the following error:

**Registration procedure, Chrometabsregister.Register in package C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\ChromeTabs_D.280.bpl raised exception class EAccessViolation: Access violation at address 6B187F63 in module 'rtl280.bpl'. Read of address 002E007A.**

**Comment by landrix** [comment]
can you test the latest source please

**Comment by yesilcimenahmet** [comment]
Hi, still same. They are compiled successfully but when I click "Install" for Design Time package it gives error.


**Registration procedure, Chrometabsregister.Register in package C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\ChromeTabs_D.280.bpl raised exception class EAccessViolation: Access violation at address 69BF7F63 in module 'rtl280.bpl'. Read of address 00000008.**

**Comment by yesilcimenahmet** [comment]
Hi, its because of "unidac_9.2.1_d28pro.exe" on Delphi 11.2 when I uninstalled it everything works nice.

**Comment by landrix** [comment]
sry, i can not give support for unidac
